version: '3.8'

services:
  app:
    container_name: mw-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    ports:
      - "8657:3000"
    environment:
      - NODE_ENV=development
